 <header>
        <a href="index.php"><img loading="lazy" class="logo" src="styles/images/logo sfc (1).png" alt="SFC_Logo"></a>
        <nav>
            <div class="menu">
            <ul>
                    <li>
                    <span><i class="fa fa-home" aria-hidden="true"></i></span>   
                    <span><a href="index.php">Home</a></span>
                    </li>
                    <li>
                    <span><i class="fa fa-sitemap" aria-hidden="true"></i></span>
                    <span><a href="about_us.php">About</a></span>
                    </li>
                    <li>
                    <span><i class="fa fa-code" aria-hidden="true"></i></span>
                    <span><a href="jobs.php">Job</a></span>
                    </li>
                    <li>
                    <span><i class="fa fa-cogs" aria-hidden="true"></i></span>
                    <span><a href="manage.php">Management</a></span>
                    </li>
                    <li>
                    <span><i class="fa fa-desktop" aria-hidden="true"></i></span>
                    <span><a href="apply.php">Apply</a></span>
                    </li>
                    <li>
                    <span><i class="fa fa-edit" aria-hidden="true"></i></span>
                    <span><a href="enhancements.php">Enhancement</a></span>
                    </li>
            </ul>
            </div>
        </nav>
        </header>